name: ploomber-workshop

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pygraphviz
  - pip
  - pip:
    - ploomber
    - pandas
    - scikit-learn
    - sklearn-evaluation
    - seaborn
    - jupyterlab
    - invoke
    - ipywidgets